import type { Metadata } from "next";
import { bodyFont } from "./fonts";
import "./globals.css";
import { Providers } from "./providers";
import MainNav from "./components/navigation/MainNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark bg-background text-foreground ${bodyFont.className}`}>
        <Providers>
          <MainNav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
